name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deploy:
    env: 
      DEPLOY_FLAG: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: BE - install dependencies
        run: npm install
      - name: BE - linting
        run: npm run lint
      - name: BE - build 
        run: npm run build
      - name: FE - build
        run: cd patientor-fe && npm install && npm run build && cp -r dist ../

  #     # - name: test
  #     #   run: npm run test
  #     # - name: e2e setup
  #     #   run: npx playwright install --with-deps
  #     # - name: e2e test
  #     #   run: npm run test:e2e
  #     # - uses: actions/upload-artifact@v4
  #     #   if: ${{ !cancelled() }}
  #     #   with:
  #     #     name: playwright-report
  #     #     path: playwright-report/
  #     #     retention-days: 30
      - name: Trigger Render deployment
        if: ${{ env.DEPLOY_FLAG == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  #     - name: Discord Notify - Success
  #       uses: stegzilla/discord-notify@v4
  #       if: ${{ env.DEPLOY_FLAG == 'true' && success() }}
  #       with:
  #         webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
  #         title: Pokedex Pipeline Notification
  #         message: "Test & Deploy Succeeded! These are the changes: **${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}**"
  #         include_image: true
  #         username: GitHub PR Notifier
  #         avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  #     - name: Discord Notify - Failure
  #       uses: stegzilla/discord-notify@v4
  #       if: failure()
  #       with:
  #         webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
  #         title: Pokedex Pipeline Notification
  #         message: "Test & Deploy Failed! Check this build: **${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}**"
  #         include_image: true
  #         username: GitHub PR Notifier
  #         avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  versioning:
    env:
      RELEASE_FLAG: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' }}
    needs: [deploy]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.RELEASE_FLAG == 'true' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
          DEFAULT_BUMP: patch
      - name: Get new tag
        if: ${{ env.RELEASE_FLAG == 'true' }}
        run: 'echo "new_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV'
      - name: Output new tag
        if: ${{ env.RELEASE_FLAG == 'true' }}
        run: 'echo "New Tag: ${{ env.new_tag }}"'
  #     - name: Discord Notify - Failure
  #       uses: stegzilla/discord-notify@v4
  #       if: failure()
  #       with:
  #         webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
  #         title: Pokedex - Versioning Failed!
  #         message: "Release Failed! Check this build: **${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}**"
  #         include_image: true
  #         username: GitHub PR Notifier
  #         avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  # health_check:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Check the deployed service URL
  #       uses: jtalk/url-health-check-action@v4
  #       with:
  #         # Check the following URLs one by one sequentially
  #         url: https://full-stack-open-pokedex-en3r.onrender.com/health-dex
  #         # Follow redirects, or just report success on 3xx status codes
  #         follow-redirect: false # Optional, defaults to "false"
  #         # Fail this action after this many failed attempts
  #         max-attempts: 3 # Optional, defaults to 1
  #         # Delay between retries
  #         retry-delay: 5s # Optional, only applicable to max-attempts > 1
  #         # Retry all errors, including 404. This option might trigger curl upgrade.
  #         retry-all: false